/*
 * Copyright (C) 2022 Jonathan Schild - All Rights Reserved
 */

use super::executor::*;
use super::Processor;

pub(super) enum AddressingModes {
    Absolute,
    AbsoluteIndexedIndirect,
    AbsoluteIndexedWithX,
    AbsoluteIndexedWithY,
    AbsoluteIndirect,
    Accumulator,
    Immediate,
    Implied,
    ProgramCounterRelative,
    Stack,
    ZeroPage,
    ZeroPageIndexedIndirect,
    ZeroPageIndexedWithX,
    ZeroPageIndexedWithY,
    ZeroPageIndirect,
    ZeroPageIndirectIndexedWithY,
    Unknown,
}

fn decode(opcode: u8) -> (fn(&mut Processor, AddressingModes, u8), AddressingModes) {
    // TODO
    match opcode {
        0x00 => (unknown, AddressingModes::Unknown),
        0x01 => (unknown, AddressingModes::Unknown),
        0x02 => (unknown, AddressingModes::Unknown),
        0x03 => (unknown, AddressingModes::Unknown),
        0x04 => (unknown, AddressingModes::Unknown),
        0x05 => (unknown, AddressingModes::Unknown),
        0x06 => (unknown, AddressingModes::Unknown),
        0x07 => (unknown, AddressingModes::Unknown),
        0x08 => (unknown, AddressingModes::Unknown),
        0x09 => (unknown, AddressingModes::Unknown),
        0x0A => (unknown, AddressingModes::Unknown),
        0x0B => (unknown, AddressingModes::Unknown),
        0x0C => (unknown, AddressingModes::Unknown),
        0x0D => (unknown, AddressingModes::Unknown),
        0x0E => (unknown, AddressingModes::Unknown),
        0x0F => (unknown, AddressingModes::Unknown),
        0x10 => (unknown, AddressingModes::Unknown),
        0x11 => (unknown, AddressingModes::Unknown),
        0x12 => (unknown, AddressingModes::Unknown),
        0x13 => (unknown, AddressingModes::Unknown),
        0x14 => (unknown, AddressingModes::Unknown),
        0x15 => (unknown, AddressingModes::Unknown),
        0x16 => (unknown, AddressingModes::Unknown),
        0x17 => (unknown, AddressingModes::Unknown),
        0x18 => (unknown, AddressingModes::Unknown),
        0x19 => (unknown, AddressingModes::Unknown),
        0x1A => (unknown, AddressingModes::Unknown),
        0x1B => (unknown, AddressingModes::Unknown),
        0x1C => (unknown, AddressingModes::Unknown),
        0x1D => (unknown, AddressingModes::Unknown),
        0x1E => (unknown, AddressingModes::Unknown),
        0x1F => (unknown, AddressingModes::Unknown),
        0x20 => (unknown, AddressingModes::Unknown),
        0x21 => (unknown, AddressingModes::Unknown),
        0x22 => (unknown, AddressingModes::Unknown),
        0x23 => (unknown, AddressingModes::Unknown),
        0x24 => (unknown, AddressingModes::Unknown),
        0x25 => (unknown, AddressingModes::Unknown),
        0x26 => (unknown, AddressingModes::Unknown),
        0x27 => (unknown, AddressingModes::Unknown),
        0x28 => (unknown, AddressingModes::Unknown),
        0x29 => (unknown, AddressingModes::Unknown),
        0x2A => (unknown, AddressingModes::Unknown),
        0x2B => (unknown, AddressingModes::Unknown),
        0x2C => (unknown, AddressingModes::Unknown),
        0x2D => (unknown, AddressingModes::Unknown),
        0x2E => (unknown, AddressingModes::Unknown),
        0x2F => (unknown, AddressingModes::Unknown),
        0x30 => (unknown, AddressingModes::Unknown),
        0x31 => (unknown, AddressingModes::Unknown),
        0x32 => (unknown, AddressingModes::Unknown),
        0x33 => (unknown, AddressingModes::Unknown),
        0x34 => (unknown, AddressingModes::Unknown),
        0x35 => (unknown, AddressingModes::Unknown),
        0x36 => (unknown, AddressingModes::Unknown),
        0x37 => (unknown, AddressingModes::Unknown),
        0x38 => (unknown, AddressingModes::Unknown),
        0x39 => (unknown, AddressingModes::Unknown),
        0x3A => (unknown, AddressingModes::Unknown),
        0x3B => (unknown, AddressingModes::Unknown),
        0x3C => (unknown, AddressingModes::Unknown),
        0x3D => (unknown, AddressingModes::Unknown),
        0x3E => (unknown, AddressingModes::Unknown),
        0x3F => (unknown, AddressingModes::Unknown),
        0x40 => (unknown, AddressingModes::Unknown),
        0x41 => (unknown, AddressingModes::Unknown),
        0x42 => (unknown, AddressingModes::Unknown),
        0x43 => (unknown, AddressingModes::Unknown),
        0x44 => (unknown, AddressingModes::Unknown),
        0x45 => (unknown, AddressingModes::Unknown),
        0x46 => (unknown, AddressingModes::Unknown),
        0x47 => (unknown, AddressingModes::Unknown),
        0x48 => (unknown, AddressingModes::Unknown),
        0x49 => (unknown, AddressingModes::Unknown),
        0x4A => (unknown, AddressingModes::Unknown),
        0x4B => (unknown, AddressingModes::Unknown),
        0x4C => (unknown, AddressingModes::Unknown),
        0x4D => (unknown, AddressingModes::Unknown),
        0x4E => (unknown, AddressingModes::Unknown),
        0x4F => (unknown, AddressingModes::Unknown),
        0x50 => (unknown, AddressingModes::Unknown),
        0x51 => (unknown, AddressingModes::Unknown),
        0x52 => (unknown, AddressingModes::Unknown),
        0x53 => (unknown, AddressingModes::Unknown),
        0x54 => (unknown, AddressingModes::Unknown),
        0x55 => (unknown, AddressingModes::Unknown),
        0x56 => (unknown, AddressingModes::Unknown),
        0x57 => (unknown, AddressingModes::Unknown),
        0x58 => (unknown, AddressingModes::Unknown),
        0x59 => (unknown, AddressingModes::Unknown),
        0x5A => (unknown, AddressingModes::Unknown),
        0x5B => (unknown, AddressingModes::Unknown),
        0x5C => (unknown, AddressingModes::Unknown),
        0x5D => (unknown, AddressingModes::Unknown),
        0x5E => (unknown, AddressingModes::Unknown),
        0x5F => (unknown, AddressingModes::Unknown),
        0x60 => (unknown, AddressingModes::Unknown),
        0x61 => (unknown, AddressingModes::Unknown),
        0x62 => (unknown, AddressingModes::Unknown),
        0x63 => (unknown, AddressingModes::Unknown),
        0x64 => (unknown, AddressingModes::Unknown),
        0x65 => (unknown, AddressingModes::Unknown),
        0x66 => (unknown, AddressingModes::Unknown),
        0x67 => (unknown, AddressingModes::Unknown),
        0x68 => (unknown, AddressingModes::Unknown),
        0x69 => (unknown, AddressingModes::Unknown),
        0x6A => (unknown, AddressingModes::Unknown),
        0x6B => (unknown, AddressingModes::Unknown),
        0x6C => (unknown, AddressingModes::Unknown),
        0x6D => (unknown, AddressingModes::Unknown),
        0x6E => (unknown, AddressingModes::Unknown),
        0x6F => (unknown, AddressingModes::Unknown),
        0x70 => (unknown, AddressingModes::Unknown),
        0x71 => (unknown, AddressingModes::Unknown),
        0x72 => (unknown, AddressingModes::Unknown),
        0x73 => (unknown, AddressingModes::Unknown),
        0x74 => (unknown, AddressingModes::Unknown),
        0x75 => (unknown, AddressingModes::Unknown),
        0x76 => (unknown, AddressingModes::Unknown),
        0x77 => (unknown, AddressingModes::Unknown),
        0x78 => (unknown, AddressingModes::Unknown),
        0x79 => (unknown, AddressingModes::Unknown),
        0x7A => (unknown, AddressingModes::Unknown),
        0x7B => (unknown, AddressingModes::Unknown),
        0x7C => (unknown, AddressingModes::Unknown),
        0x7D => (unknown, AddressingModes::Unknown),
        0x7E => (unknown, AddressingModes::Unknown),
        0x7F => (unknown, AddressingModes::Unknown),
        0x80 => (unknown, AddressingModes::Unknown),
        0x81 => (unknown, AddressingModes::Unknown),
        0x82 => (unknown, AddressingModes::Unknown),
        0x83 => (unknown, AddressingModes::Unknown),
        0x84 => (unknown, AddressingModes::Unknown),
        0x85 => (unknown, AddressingModes::Unknown),
        0x86 => (unknown, AddressingModes::Unknown),
        0x87 => (unknown, AddressingModes::Unknown),
        0x88 => (unknown, AddressingModes::Unknown),
        0x89 => (unknown, AddressingModes::Unknown),
        0x8A => (unknown, AddressingModes::Unknown),
        0x8B => (unknown, AddressingModes::Unknown),
        0x8C => (unknown, AddressingModes::Unknown),
        0x8D => (unknown, AddressingModes::Unknown),
        0x8E => (unknown, AddressingModes::Unknown),
        0x8F => (unknown, AddressingModes::Unknown),
        0x90 => (unknown, AddressingModes::Unknown),
        0x91 => (unknown, AddressingModes::Unknown),
        0x92 => (unknown, AddressingModes::Unknown),
        0x93 => (unknown, AddressingModes::Unknown),
        0x94 => (unknown, AddressingModes::Unknown),
        0x95 => (unknown, AddressingModes::Unknown),
        0x96 => (unknown, AddressingModes::Unknown),
        0x97 => (unknown, AddressingModes::Unknown),
        0x98 => (unknown, AddressingModes::Unknown),
        0x99 => (unknown, AddressingModes::Unknown),
        0x9A => (unknown, AddressingModes::Unknown),
        0x9B => (unknown, AddressingModes::Unknown),
        0x9C => (unknown, AddressingModes::Unknown),
        0x9D => (unknown, AddressingModes::Unknown),
        0x9E => (unknown, AddressingModes::Unknown),
        0x9F => (unknown, AddressingModes::Unknown),
        0xA0 => (unknown, AddressingModes::Unknown),
        0xA1 => (unknown, AddressingModes::Unknown),
        0xA2 => (unknown, AddressingModes::Unknown),
        0xA3 => (unknown, AddressingModes::Unknown),
        0xA4 => (unknown, AddressingModes::Unknown),
        0xA5 => (unknown, AddressingModes::Unknown),
        0xA6 => (unknown, AddressingModes::Unknown),
        0xA7 => (unknown, AddressingModes::Unknown),
        0xA8 => (unknown, AddressingModes::Unknown),
        0xA9 => (unknown, AddressingModes::Unknown),
        0xAA => (unknown, AddressingModes::Unknown),
        0xAB => (unknown, AddressingModes::Unknown),
        0xAC => (unknown, AddressingModes::Unknown),
        0xAD => (unknown, AddressingModes::Unknown),
        0xAE => (unknown, AddressingModes::Unknown),
        0xAF => (unknown, AddressingModes::Unknown),
        0xB0 => (unknown, AddressingModes::Unknown),
        0xB1 => (unknown, AddressingModes::Unknown),
        0xB2 => (unknown, AddressingModes::Unknown),
        0xB3 => (unknown, AddressingModes::Unknown),
        0xB4 => (unknown, AddressingModes::Unknown),
        0xB5 => (unknown, AddressingModes::Unknown),
        0xB6 => (unknown, AddressingModes::Unknown),
        0xB7 => (unknown, AddressingModes::Unknown),
        0xB8 => (unknown, AddressingModes::Unknown),
        0xB9 => (unknown, AddressingModes::Unknown),
        0xBA => (unknown, AddressingModes::Unknown),
        0xBB => (unknown, AddressingModes::Unknown),
        0xBC => (unknown, AddressingModes::Unknown),
        0xBD => (unknown, AddressingModes::Unknown),
        0xBE => (unknown, AddressingModes::Unknown),
        0xBF => (unknown, AddressingModes::Unknown),
        0xC0 => (unknown, AddressingModes::Unknown),
        0xC1 => (unknown, AddressingModes::Unknown),
        0xC2 => (unknown, AddressingModes::Unknown),
        0xC3 => (unknown, AddressingModes::Unknown),
        0xC4 => (unknown, AddressingModes::Unknown),
        0xC5 => (unknown, AddressingModes::Unknown),
        0xC6 => (unknown, AddressingModes::Unknown),
        0xC7 => (unknown, AddressingModes::Unknown),
        0xC8 => (unknown, AddressingModes::Unknown),
        0xC9 => (unknown, AddressingModes::Unknown),
        0xCA => (unknown, AddressingModes::Unknown),
        0xCB => (unknown, AddressingModes::Unknown),
        0xCC => (unknown, AddressingModes::Unknown),
        0xCD => (unknown, AddressingModes::Unknown),
        0xCE => (unknown, AddressingModes::Unknown),
        0xCF => (unknown, AddressingModes::Unknown),
        0xD0 => (unknown, AddressingModes::Unknown),
        0xD1 => (unknown, AddressingModes::Unknown),
        0xD2 => (unknown, AddressingModes::Unknown),
        0xD3 => (unknown, AddressingModes::Unknown),
        0xD4 => (unknown, AddressingModes::Unknown),
        0xD5 => (unknown, AddressingModes::Unknown),
        0xD6 => (unknown, AddressingModes::Unknown),
        0xD7 => (unknown, AddressingModes::Unknown),
        0xD8 => (unknown, AddressingModes::Unknown),
        0xD9 => (unknown, AddressingModes::Unknown),
        0xDA => (unknown, AddressingModes::Unknown),
        0xDB => (unknown, AddressingModes::Unknown),
        0xDC => (unknown, AddressingModes::Unknown),
        0xDD => (unknown, AddressingModes::Unknown),
        0xDE => (unknown, AddressingModes::Unknown),
        0xDF => (unknown, AddressingModes::Unknown),
        0xE0 => (unknown, AddressingModes::Unknown),
        0xE1 => (unknown, AddressingModes::Unknown),
        0xE2 => (unknown, AddressingModes::Unknown),
        0xE3 => (unknown, AddressingModes::Unknown),
        0xE4 => (unknown, AddressingModes::Unknown),
        0xE5 => (unknown, AddressingModes::Unknown),
        0xE6 => (unknown, AddressingModes::Unknown),
        0xE7 => (unknown, AddressingModes::Unknown),
        0xE8 => (unknown, AddressingModes::Unknown),
        0xE9 => (unknown, AddressingModes::Unknown),
        0xEA => (unknown, AddressingModes::Unknown),
        0xEB => (unknown, AddressingModes::Unknown),
        0xEC => (unknown, AddressingModes::Unknown),
        0xED => (unknown, AddressingModes::Unknown),
        0xEE => (unknown, AddressingModes::Unknown),
        0xEF => (unknown, AddressingModes::Unknown),
        0xF0 => (unknown, AddressingModes::Unknown),
        0xF1 => (unknown, AddressingModes::Unknown),
        0xF2 => (unknown, AddressingModes::Unknown),
        0xF3 => (unknown, AddressingModes::Unknown),
        0xF4 => (unknown, AddressingModes::Unknown),
        0xF5 => (unknown, AddressingModes::Unknown),
        0xF6 => (unknown, AddressingModes::Unknown),
        0xF7 => (unknown, AddressingModes::Unknown),
        0xF8 => (unknown, AddressingModes::Unknown),
        0xF9 => (unknown, AddressingModes::Unknown),
        0xFA => (unknown, AddressingModes::Unknown),
        0xFB => (unknown, AddressingModes::Unknown),
        0xFC => (unknown, AddressingModes::Unknown),
        0xFD => (unknown, AddressingModes::Unknown),
        0xFE => (unknown, AddressingModes::Unknown),
        0xFF => (unknown, AddressingModes::Unknown),
    }
}
